[package]
name = "backend-rust"
version = "0.0.1"
authors = ["Paul Seydel <seydel@zib.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.5"
